<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      description.gazebo.xacro
\authors   Raffaello Bonghi <raffaello.bonghi@officinerobotiche.it
\copyright Copyright (c) 2015, Officine Robotiche, All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot name="dude_robot_gazebo" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ros_dude_gazebo)/urdf/xtion_camera.gazebo.xacro"/>

  <xacro:include filename="$(find dude_description)/urdf/dude.urdf.xacro" />
  <xacro:dude_robot_gazebo />

  <!-- base_link -->
  <gazebo reference="base_link">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <!-- column_body_Link -->
  <gazebo reference="column_body_Link">
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- electronics_Link -->
  <gazebo reference="electronics_Link">
    <material>Gazebo/Green</material>
  </gazebo>

  <!-- wall_body_Link -->
  <gazebo reference="wall_body_Link">
    <material>Gazebo/White</material>
  </gazebo>

  <!-- battery_Link -->
  <gazebo reference="battery_Link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!--<xacro:xtion_camera_gazebo prefix="xtion_camera"/>-->

  <!-- Differential drive -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
    <alwaysOn>true</alwaysOn>
    <updateRate>10.0</updateRate>
     <leftJoint>Left</leftJoint>
    <rightJoint>Right</rightJoint>
    <wheelSeparation>${wheel_offset_y*2}</wheelSeparation>
    <wheelDiameter>${wheel_radius*2}</wheelDiameter>
    <torque>20</torque>
    <commandTopic>cmd_vel</commandTopic>
    <odometryTopic>odom</odometryTopic>
    <odometryFrame>odom</odometryFrame>
    <robotBaseFrame>base_link</robotBaseFrame>
    <publishWheelTF>true</publishWheelTF>
    <publishWheelJointState>true</publishWheelJointState>
    </plugin>
  </gazebo>

  <!-- hokuyo -->
  <gazebo reference="rgbd_camera_depth_frame">
    <sensor type="gpu_ray" name="head_hokuyo_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true
               reading. -->
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_gpu_laser.so">
        <topicName>scan</topicName>
        <frameName>rgbd_camera_depth_frame</frameName>
      </plugin>
    </sensor>
  </gazebo>


</robot>
